# Generated by Django 5.1.4 on 2025-01-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_available_students_instructor_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor_available',
            old_name='name',
            new_name='Instructor_name',
        ),
        migrations.RenameField(
            model_name='instructor_available',
            old_name='student_number',
            new_name='instructor_number',
        ),
    ]
