# Generated by Django 5.1.4 on 2025-01-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_name_instructor_available_instructor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_available',
            name='instructor',
        ),
    ]
