# Generated by Django 5.1.4 on 2025-01-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_available_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('joined_in', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_period', models.IntegerField()),
                ('student_number', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
