# Generated by Django 5.1.4 on 2025-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_student_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_available',
            name='course_period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
